//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Soma.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDS_SUC_ITEMTRANSFORM           105
#define IDS_CAPTURE                     106
#define IDS_LOGOUT_AFTER                107
#define IDS_LOGOUT_CANCEL               108
#define IDS_REPAIRING_ITEM              109
#define IDS_GIGGLED                     110
#define IDS_SPECIAL_52                  111
#define IDR_MAINFRAME                   128
#define IDR_SOMATYPE                    129
#define IDS_EXCHANGE_ASK                129
#define IDD_DIALOG_LOGIN                130
#define IDS_EXCHANGE_WAIT               130
#define IDS_EXCHANGE_ACK                131
#define IDB_BITMAP1                     131
#define IDS_EXCHANGE_SUCCESS            132
#define IDD_DIALOG_PACKETLOG            132
#define IDS_EXCHANGE_FAIL               133
#define IDS_EXCHANGE_FAIL1              134
#define IDS_EXCHANGE_FAIL2              135
#define IDS_EXCHANGE_FAIL3              136
#define IDS_EXCHANGE_CANCEL             137
#define IDS_EXCHANGE_DENY               138
#define IDS_AUCTION_SUCCESS             139
#define IDS_AUCTION_FAIL                140
#define IDS_GUILD_CHANGE_SYMBOL         141
#define IDS_GUILD_INVALID_SYMBOL        142
#define IDS_ALREADY_JOIN                143
#define IDS_MAKEGUILD_SMALL_MONEY       144
#define IDS_MAKEGUILD_SMALL_LEVEL       145
#define IDS_MAKEGUILD_INVALID_GUILD_NAME 146
#define IDS_MAKEGUILD_INVALID_GUILD_INFO 147
#define IDS_MAKEGUILD_SAME_GUILD_NAME   148
#define IDS_MAKEGUILD_GUILD_FULL        149
#define IDS_FAIL_CHANGE_TAXRATE         150
#define IDS_MAKEGUILD_SYSTEM_ERROR      151
#define IDS_ASK_CHANGE_MEMBER           152
#define IDS_NOT_GUILD_USER              153
#define IDS_ABSENT_REQ_USER             154
#define IDS_ASK_CANCEL_APPLY            155
#define IDS_ASK_REMOVE_MEMBER           156
#define IDS_ASK_QUIT_MASTER             157
#define IDS_ASK_QUIT_MEMBER             158
#define IDS_ASK_DISSOLVE_GUILD          159
#define IDS_SUC_DISSOLVE_GUILD          160
#define IDS_ABSENT_GUILD_NAME           161
#define IDS_ASKUSER_UNKNOWN_ERR         162
#define IDS_SUC_DONATION                163
#define IDS_FAIL_DONATION               164
#define IDS_ALREADY_JOIN_REQ            165
#define IDS_EMPTY_GUILD_DESC            166
#define IDS_SMALL_RANK                  167
#define IDS_GUILDREQ_SYSTEM_ERROR       168
#define IDS_SUC_MAKE_GUILD              169
#define IDS_JOIN_SYSTEM_ERROR           170
#define IDS_ABSENT_JOIN_REQ             171
#define IDS_ABSENT_JOIN                 172
#define IDS_REMOVE_SYSTEM_ERROR         173
#define IDS_SUC_JOINGUILD               174
#define IDS_DISSOLVE_SYSTEM_ERROR       175
#define IDS_NOMORE_REPAIR               176
#define IDS_NO_REPAIR                   177
#define IDS_NOMONEY_REPAIR              178
#define IDS_DESTROY_ITEM                179
#define IDS_FAIL_REPAIR                 180
#define IDS_SUC_REPAIR                  181
#define IDS_SUC_QUIT_MEMBER             182
#define IDS_CHANGE_NEED_EMPTY_RANK      183
#define IDS_CHANGE_INVALID_RANK         184
#define IDS_CHANGE_SYSTEM_ERROR         185
#define IDS_CPOS_INVALID_RANK           186
#define IDS_CPOS_INVALID_GUILD_CALL_NAME 187
#define IDS_CPOS_SYSTEM_ERROR           188
#define IDS_EMPTY_GUILD                 189
#define IDS_SUC_CANCEL_APPLY            190
#define IDS_EMPTY_APPLICATION           191
#define IDS_LESS_MONEY                  192
#define IDS_SUC_WITHDRAW_DONATION       193
#define IDS_FAIL_WITHDRAW_DONATION      194
#define IDS_REGISTER_ITEM               195
#define IDS_FAIL_REG_ITEM               196
#define IDS_TAKE_BACK_ITEM              197
#define IDS_PARTY_WAIT                  200
#define IDS_PARTY_FAIL                  201
#define IDS_PARTY_REQ                   202
#define IDS_GUILD_WAR_REQ               203
#define IDS_GUILD_WAR_WAIT              204
#define IDS_GUILD_WAR_REQ_DENY          205
#define IDS_GUILD_WAR_CANCEL            206
#define IDS_GUILD_WAR_START             207
#define IDS_REPAIR_REQ                  208
#define IDS_REPAIR_WAIT                 209
#define IDS_REPAIR_CANCEL               210
#define IDS_REPAIR_PLAYER_STR           211
#define IDS_CANCEL_REQUEST              212
#define IDS_REFUSE_REQUEST              213
#define IDS_GUILD_ALLY_REQUEST          214
#define IDS_FAILED_CONNECT              215
#define IDS_BATTLEMODE                  300
#define IDS_CHARACTER                   301
#define IDS_INVENTORY                   302
#define IDS_CHAT                        303
#define IDS_MAGIC                       304
#define IDS_OPTION                      305
#define IDS_HELP                        306
#define IDS_NEWCHAR_DEFAULT             700
#define IDS_NEWCHAR_POWERTYPE           701
#define IDS_NEWCHAR_SPEEDTYPE           702
#define IDS_NEWCHAR_MAGICTYPE           703
#define IDS_NEWCHAR_BALACETYPE          704
#define IDS_NEWCHAR_STR                 705
#define IDS_NEWCHAR_DEX                 706
#define IDS_NEWCHAR_INT                 707
#define IDS_NEWCHAR_WIS                 708
#define IDS_NEWCHAR_CHAR                709
#define IDS_NEWCHAR_CON                 710
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_EDIT3                       1002
#define IDC_CHECK1                      1003
#define IDC_EDIT4                       1004
#define IDS_ASK_MAKE_GUILD              57346
#define IDS_NEW_DEV_CHAR                61204
#define IDS_NEWCHAR_SWORDSMAN           61205
#define IDS_NEWCHAR_WARRIOR             61206
#define IDS_NEWCHAR_KNIGHT              61207
#define IDS_NEWCHAR_ARCHER              61208
#define IDS_NEWCHAR_FIGHTER             61209
#define IDS_NEWCHAR_WIZARD              61210
#define IDS_NO_OCCUPATION               61211
#define IDS_CONNECT_GAME                61212
#define IDS_CONNECT_ACCOUNT             61213
#define IDS_FREE_LOGIN                  61214
#define IDS_PAY_LOGIN                   61215
#define IDS_7DAY_TRIAL                  61216
#define IDS_SPECIAL_4                   61217
#define IDS_SPECIAL_8                   61218
#define IDS_SPECIAL_9                   61219
#define IDS_SPECIAL_11                  61220
#define IDS_SPECIAL_12                  61221
#define IDS_SPECIAL_13                  61222
#define IDS_SPECIAL_14                  61223
#define IDS_SPECIAL_15                  61224
#define IDS_SPECIAL_16                  61225
#define IDS_SPECIAL_17                  61226
#define IDS_SPECIAL_18                  61227
#define IDS_SPECIAL_19                  61228
#define IDS_SPECIAL_20                  61229
#define IDS_SPECIAL_21                  61230
#define IDS_SPECIAL_22                  61231
#define IDS_SPECIAL_23                  61232
#define IDS_SPECIAL_24                  61233
#define IDS_SPECIAL_25                  61234
#define IDS_SPECIAL_26                  61235
#define IDS_SPECIAL_27                  61236
#define IDS_SPECIAL_28                  61237
#define IDS_SPECIAL_29                  61238
#define IDS_SPECIAL_30                  61239
#define IDS_SPECIAL_34                  61240
#define IDS_SPECIAL_35                  61241
#define IDS_SPECIAL_36                  61245
#define IDS_SPECIAL_37                  61246
#define IDS_SPECIAL_40                  61252
#define IDS_SPECIAL_41                  61253
#define IDS_SPECIAL_42                  61254
#define IDS_SPECIAL_43                  61255
#define IDS_SPECIAL_44                  61256
#define IDS_SPECIAL_45                  61257
#define IDS_SPECIAL_46                  61258
#define IDS_SPECIAL_47                  61259
#define IDS_SPECIAL_55                  61260
#define IDS_SPECIAL_58                  61261
#define IDS_SPECIAL_59                  61262
#define IDS_SPECIAL_48                  61263
#define IDS_AUCTION_MSG_1               61264
#define IDS_AUCTION_MSG_2               61265
#define IDS_AUCTION_MSG_3               61266
#define IDS_AUCTION_MSG_4               61267
#define IDS_AUCTION_MSG_5               61268
#define IDS_AUCTION_MSG_6               61269
#define IDS_AUCTION_MSG_7               61270
#define IDS_AUCTION_MSG_8               61271
#define IDS_AUCTION_MSG_9               61272
#define IDS_AUCTION_MSG_10              61273
#define IDS_AUCTION_MSG_11              61274
#define IDS_AUCTION_MSG_12              61275
#define IDS_AUCTION_MSG_13              61276
#define IDS_AUCTION_MSG_14              61277
#define IDS_AUCTION_MSG_15              61278
#define IDS_AUCTION_MSG_16              61279
#define IDS_AUCTION_MSG_17              61280
#define IDS_AUCTION_MSG_18              61281
#define IDS_AUCTION_MSG_19              61282
#define IDS_AUCTION_MSG_20              61283
#define IDS_AUCTION_MSG_21              61284
#define IDS_AUCTION_MSG_22              61285

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
